###############################################################################
#	FILE		:	Makefile
#	PROJECT		:	hevc-cut tool
#	AUTHOR		:	Michael A. Uman <Michael_Uman@sigmadesigns.com>
#	DATE		:	September 18, 2013
###############################################################################

TARGET_TYPE=statlib
CPP_SOURCES=bitbuffer.cpp
LIBNAME=libbitbuffer

CFLAGS=-Wall -O3 -fexpensive-optimizations 
#CFLAGS=-g3 -c

include ../build/buildsys.mk

